title: Blog
subtitle: 记录生活中的点点滴滴
description: 正因为有忘也忘不了的回忆，才会变得坚强，这就是所谓的成长吧！
keywords: null
author: Xiaopc767d
language: zh-CN
timezone: Asia/Shanghai
url: "https://bipch.cn/"
root: /
permalink: ":subtitle/"
permalink_defaults: null

pretty_urls:
  trailing_index: true
  trailing_html: true

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ":lang"
skip_render: README.md
new_post_name: ":title.md"
default_layout: post
titlecase: false

external_link:
  enable: true
  field: site
  exclude: ""

filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

highlight:
  enable: true
  line_number: true
  auto_detect: true

index_generator:
  path: ""
  per_page: 10
  order_by: "-date"

default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: "HH:mm:ss"
use_date_for_updated: false
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null

# 主题
theme: next

#deploy:
#  type: git
#  repo: git@github.com:bpc99/hexo.git
#  branch: master

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Extensions
## Plugins: http://hexo.io/plugins/
#RSS订阅
plugin:
  - hexo-generator-feed

#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20